Fix CheckBox Command property error using EventToCommandBehavior
Problem: CheckBox in .NET MAUI does not have a Command property like Button
Error: XFC0009 - No property 'Command' found on CheckBox (line 138)

Solution: Used CommunityToolkit.Maui EventToCommandBehavior to convert
CheckedChanged event to command execution.

Changed from:
<CheckBox Command="{Binding...}" CommandParameter="{Binding Id}" />

To:
<CheckBox>
  <CheckBox.Behaviors>
    <toolkit:EventToCommandBehavior
      EventName="CheckedChanged"
      Command="{Binding...}"
      CommandParameter="{Binding Id}" />
  </CheckBox.Behaviors>
</CheckBox>